name: mailer
version: 3.1.0
description: >
  Compose and send emails from Dart.
  Supports file attachments and HTML emails
authors:
- Kai Sellgren <kaisellgren@gmail.com>
- Dan Rubel <danrubel@google.com>
- Matthew Butler <butler.matthew@gmail.com>
- Christian Loitsch <christian@loitsch.com>
- Piotr Kroll <piotr@kroll.eu>
- Jonathan Rezende <jonathan@jode.com.br>
homepage: https://github.com/kaisellgren/mailer
environment:
  sdk: '>=2.2.2 <3.0.0'
dependencies:
  async: '>=2.0.0 <3.0.0'
  logging: '>0.0.1 <1.0.0'
  intl: '>0.9.0 <1.0.0'
  mime: '>0.9.0 <1.0.0'
  path: '>0.9.0 <2.0.0'
  pedantic: '>=1.5.0 <2.0.0'

dev_dependencies:
  args: '>=1.5.0 <2.0.0'
  test: '>=1.5.1 <2.0.0'
  googleapis_auth: ^0.2.7
