name: mailer
version: 1.2.3
description: >
  Compose and send emails from Dart.
  Supports file attachments, HTML emails and multiple transport methods.
authors:
- Kai Sellgren <kaisellgren@gmail.com>
- Dan Rubel <danrubel@google.com>
- Matthew Butler <butler.matthew@gmail.com>
- Christian Loitsch <christian@loitsch.com>
homepage: http://github.com/kaisellgren/mailer
environment:
  sdk: '>=1.17.0 <3.0.0'
dependencies:
  dart2_constant: ^1.0.0
  mime: '>0.9.0 <1.0.0'
  logging: '<1.0.0'
  path: '>0.9.0 <2.0.0'
  intl: '>0.9.0 <1.0.0'
  charcode: '<2.0.0'
dev_dependencies:
  args: '>0.13.0 <2.0.0'
  test: '>0.12.0 <2.0.0'
