name: mailer
version: 2.0.0
description: >
  Compose and send emails from Dart.
  Supports file attachments, HTML emails and multiple transport methods.
authors:
- Kai Sellgren <kaisellgren@gmail.com>
- Dan Rubel <danrubel@google.com>
- Matthew Butler <butler.matthew@gmail.com>
- Christian Loitsch <christian@loitsch.com>
homepage: http://github.com/kaisellgren/mailer
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  async: ^2.0.8
  logging: ^0.11.3+2
  intl: ^0.15.7
  collection: ^1.14.11
  mime: ^0.9.6+2
  args: ^1.5.0
